services:
  postgres:
    image:  pgvector/pgvector:pg16

    container_name: central-db

    environment:
      POSTGRES_DB: central_db
      POSTGRES_USER: central_admin
      POSTGRES_PASSWORD: centralDb13


    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
