"""create_papers_and_paper_chunks_table

Revision ID: f1c0cdf795dd
Revises: cf7f9c740d00
Create Date: 2026-06-30 08:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'f1c0cdf795dd'
down_revision: Union[str, None] = 'cf7f9c740d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'papers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('doi', sa.Text(), nullable=True),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('abstract', sa.Text(), nullable=True),
        sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('publication_date', sa.DateTime(), nullable=True),
        sa.Column('journal', sa.Text(), nullable=True),
        sa.Column('pmid', sa.Text(), nullable=True),
        sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('full_text', sa.Text(), nullable=True),
        sa.Column('source', sa.Text(), nullable=True),
        sa.Column('jats_xml', sa.Text(), nullable=True),
        sa.Column('ocr_text', sa.Text(), nullable=True),
        sa.Column('language', sa.Text(), nullable=True),
        sa.Column('word_count', sa.Integer(), nullable=True),
        sa.Column('citation_count', sa.Integer(), nullable=True),
        sa.Column('status', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('embedding', Vector(384), nullable=True),
        sa.Column('external_id', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('doi', 'source', name='uq_papers_doi_source')
    )
    op.create_index('ix_papers_doi', 'papers', ['doi'], unique=False)
    op.create_index('ix_papers_full_text_gin', 'papers', ['full_text'], postgresql_using='gin')
    op.create_index('ix_papers_embedding_hnsw', 'papers', ['embedding'], postgresql_using='hnsw')
    op.create_index('ix_papers_external_id', 'papers', ['external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))

    op.create_table(
        'paper_chunks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('paper_id', sa.Integer(), nullable=False),
        sa.Column('chunk_text', sa.Text(), nullable=False),
        sa.Column('chunk_index', sa.Integer(), nullable=False),
        sa.Column('embedding', Vector(384), nullable=True),
        sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_chunks_paper_id', 'paper_chunks', ['paper_id'], unique=False)
    op.create_index('ix_paper_chunks_embedding_hnsw', 'paper_chunks', ['embedding'], postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paper_chunks_embedding_hnsw', table_name='paper_chunks', postgresql_using='hnsw')
    op.drop_index('ix_paper_chunks_paper_id', table_name='paper_chunks')
    op.drop_table('paper_chunks')
    op.drop_index('ix_papers_external_id', table_name='papers', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_index('ix_papers_embedding_hnsw', table_name='papers', postgresql_using='hnsw')
    op.drop_index('ix_papers_full_text_gin', table_name='papers', postgresql_using='gin')
    op.drop_index('ix_papers_doi', table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
